Update Vagrantfile

diff --git a/virtualbox-3nodes/Vagrantfile b/virtualbox-3nodes/Vagrantfile
--- a/virtualbox-3nodes/Vagrantfile
+++ b/virtualbox-3nodes/Vagrantfile
@@ -2,7 +2,9 @@
 # vi: set ft=ruby :
 
 # generate SSH key in the folder if they don't exist already
-system('[ -f ssh_key ] && echo "(Using existing ssh key)" || ssh-keygen -f ssh_key -P ""')
+system('echo "Installing vagrant plugin required and generate SSH key for Openstack cluster..."')
+system('[ -f ssh_key ] && echo "An existing key has been detected and will be used" || ssh-keygen -f ssh_key -P ""')
+system('[ $(vagrant plugin list | grep -c vagrant-disksize) = "0" ] && vagrant plugin install vagrant-disksize || echo "Vagrant plugin detected"')
 
 Vagrant.configure("2") do |config|
 
@@ -19,8 +21,8 @@ apt-get -qy install python-dev libffi-dev gcc libssl-dev python-selinux python-s
 pip install ansible 
 
 # declare static host part of the cluster
-echo "192.168.50.68 openstack" >>  /etc/hosts
-echo "192.168.50.75 provision" >> /etc/hosts
+echo "192.168.50.68 openstack" >> /etc/hosts
+echo "192.168.50.75 deploy" >> /etc/hosts
 echo "192.168.50.76 controller01" >> /etc/hosts
 echo "192.168.50.77 controller02" >> /etc/hosts
 echo "192.168.50.78 compute01" >> /etc/hosts
@@ -59,6 +61,10 @@ SHELL
 
   # this section is reponsible for installing Kolla on the deploy host and then trigger the deployment
   $openstack_install = <<-SHELL
+# fixing hostname
+hostname deploy
+echo "deploy" > /etc/hostname
+
 # installing kolla from pip repo
 pip install kolla-ansible
 
@@ -66,7 +72,8 @@ pip install kolla-ansible
 cp -r /usr/local/share/kolla-ansible/etc_examples/kolla /etc/ 
 
 # altering configuration to match our configuration and choices in terms of distribution, network and virtualization engine (QEMU because Virtualbox does not do nested virtualization)
-# we are adding centralized logging, which will install a ELK instance listening on http://192.168.50.68:5601
+# a) we are adding centralized logging, which will install a ELK instance listening on http://192.168.50.68:5601
+# b) we need to change keepalived virtual router id in order to elimiate conflict with concurrent openstack on the network
 sed -i s/'#openstack_release: ""'/'openstack_release: "rocky"'/g /etc/kolla/globals.yml
 sed -i s/'kolla_internal_vip_address: "10.10.10.254"'/'kolla_internal_vip_address: "192.168.50.68"'/g /etc/kolla/globals.yml
 sed -i s/'#network_interface: "eth0"'/'network_interface: "enp0s8"'/g /etc/kolla/globals.yml
@@ -74,6 +81,7 @@ sed -i s/'#network_interface: "eth0"'/'network_interface: "enp0s8"'/g /etc/kolla
 sed -i s/'#neutron_external_interface: "eth1"'/'neutron_external_interface: "enp0s9"'/g /etc/kolla/globals.yml
 sed -i s/'#nova_compute_virt_type: "kvm"'/'nova_compute_virt_type: "qemu"'/g /etc/kolla/globals.yml
 sed -i s/'#enable_central_logging: "no"'/'enable_central_logging: "yes"'/g /etc/kolla/globals.yml
+sed -i s/'#keepalived_virtual_router_id: "51"'/'keepalived_virtual_router_id: "251"'/g /etc/kolla/globals.yml
 
 # Generating password and keeping a copy in this directory
 kolla-genpwd 
@@ -157,8 +165,8 @@ SHELL
   # a compute resource
   config.vm.define "compute01" do |compute01|
     compute01.vm.box = "ubuntu/xenial64"
+    compute01.disksize.size = '120GB' # require vagrant plugin disk-resize
 
-    compute01.disksize.size = '120GB'
     compute01.vm.provider "virtualbox" do |v|
       v.name = "kolla-multinode-compute01"
       v.memory = 8192 
